name: Bug Report
description: File a bug report to help us improve EZpanso
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please provide as much detail as possible.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What environment are you running EZpanso on?
      placeholder: "macOS 14.5, Python 3.11.2, PyQt6 6.9.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open EZpanso
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Messages
      description: If applicable, copy and paste any error messages here
      render: shell

  - type: textarea
    id: yaml
    attributes:
      label: Sample YAML
      description: If the bug relates to specific YAML content, please provide a minimal example
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
