name: Feature Request
description: Suggest a new feature for EZpanso
title: "[Feature]: "
labels: ["feature", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: Describe any alternative solutions you've thought about...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work
      placeholder: Show mockups, workflows, or examples of the feature in action...

  - type: checkboxes
    id: scope
    attributes:
      label: Feature Scope
      description: What areas would this feature affect?
      options:
        - label: User Interface
        - label: File handling
        - label: Snippet editing
        - label: Import/Export
        - label: Performance
        - label: Cross-platform compatibility
        - label: Keyboard shortcuts
        - label: Settings/Configuration

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Essential for my use case
        - Blocking my adoption of EZpanso

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
