name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
        
    - name: Install dependencies
      run: poetry install
      
    - name: Install create-dmg
      run: brew install create-dmg
      
    - name: Build macOS app
      run: |
        chmod +x build_macos.sh
        ./build_macos.sh
        
    - name: Upload macOS DMG
      uses: actions/upload-artifact@v3
      with:
        name: EZpanso-macOS
        path: EZpanso-*.dmg
        
    - name: Upload macOS App
      uses: actions/upload-artifact@v3
      with:
        name: EZpanso-macOS-App
        path: dist/EZpanso.app

  create-release:
    needs: [build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          EZpanso-macOS/*.dmg
        body: |
          ## 🎉 EZpanso Release
          
          ### 📥 Downloads
          - **macOS**: Download the `.dmg` file below
          - **Windows/Linux**: Use Python installation (see README)
          
          ### 🚀 What's New
          See [CHANGELOG.md](CHANGELOG.md) for full details.
          
          ### 🛠️ Installation
          **macOS**: Download the DMG, open it, and drag EZpanso to Applications.
          
          **Python**: `pip install -r requirements.txt && python main.py`
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
